project_id = "kivwoupcuguiuwkxwphc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.receive-raw-material]
enabled = true
verify_jwt = true
import_map = "./functions/receive-raw-material/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/receive-raw-material/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/receive-raw-material/*.html" ]

[functions.issue-raw-material]
enabled = true
verify_jwt = true
import_map = "./functions/issue-raw-material/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/issue-raw-material/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/issue-raw-material/*.html" ]

[functions.post-adjustment]
enabled = true
verify_jwt = true
import_map = "./functions/post-adjustment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/post-adjustment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/post-adjustment/*.html" ]

[functions.post-transfer]
enabled = true
verify_jwt = true
import_map = "./functions/post-transfer/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/post-transfer/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/post-transfer/*.html" ]

[functions.receive-finished-goods]
enabled = true
verify_jwt = true
import_map = "./functions/receive-finished-goods/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/receive-finished-goods/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/receive-finished-goods/*.html" ]

[functions.issue-finished-goods]
enabled = true
verify_jwt = true
import_map = "./functions/issue-finished-goods/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/issue-finished-goods/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/issue-finished-goods/*.html" ]

[functions.post-goods-receipt]
enabled = true
verify_jwt = true
import_map = "./functions/post-goods-receipt/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/post-goods-receipt/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/post-goods-receipt/*.html" ]

[functions.post-delivery-order]
enabled = true
verify_jwt = true
import_map = "./functions/post-delivery-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/post-delivery-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/post-delivery-order/*.html" ]
